[project]
name = "recipe-mapper"
version = "0.1.0"
description = "Convert Obsidian markdown recipe files to structured JSON."
requires-python = ">=3.10"

dependencies = []

[project.optional-dependencies]
dev = [
  "pytest>=8.0",
]

[tool.pytest.ini_options]
addopts = "-q"
testpaths = ["tests"]